
server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: hgw
      password: hgw11
      driver-class-name: com.mysql.jdbc.Driver
  application:
       name: service-client