
server:
  port: 8664


spring:
  application:
      name: FeignService
  main:
      allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/



